title: Zelda Rose documentation
author: Lo√Øc Grobol
logo: logo.png
repository:
  url: https://github.com/loicgrobol/zeldarose
  path_to_book: docs 

html:
  use_issues_button: true
  use_repository_button: true

execute:
  execute_notebooks: force